import { ChatRoom } from '../types';
import { Colors } from '../theme/colors';

export const ROOMS: ChatRoom[] = [
  {
    id: 'general',
    name: 'General',
    description: 'Open conversation for everyone',
    icon: '🌐',
    isAdult: false,
    color: Colors.primary,
  },
  {
    id: 'tech',
    name: 'Tech & Code',
    description: 'Programming and technology',
    icon: '💻',
    isAdult: false,
    color: '#4FC3F7',
  },
  {
    id: 'gaming',
    name: 'Gaming',
    description: 'Games and eSports',
    icon: '🎮',
    isAdult: false,
    color: '#7C4DFF',
  },
  {
    id: 'music',
    name: 'Music',
    description: 'Music discussion and discovery',
    icon: '🎵',
    isAdult: false,
    color: '#E040FB',
  },
  {
    id: 'cinema',
    name: 'Movies & TV',
    description: 'Films and series',
    icon: '🎬',
    isAdult: false,
    color: '#FF5252',
  },
  {
    id: 'crypto',
    name: 'Crypto & Finance',
    description: 'Trading and investments',
    icon: '📈',
    isAdult: false,
    color: '#69F0AE',
  },
  {
    id: 'art',
    name: 'Art & Design',
    description: 'Creative works and design',
    icon: '🎨',
    isAdult: false,
    color: '#FF6E40',
  },
  {
    id: 'fitness',
    name: 'Fitness & Health',
    description: 'Workouts and nutrition',
    icon: '🏋️',
    isAdult: false,
    color: '#00E676',
  },
  {
    id: 'books',
    name: 'Books & Knowledge',
    description: 'Reading and education',
    icon: '📚',
    isAdult: false,
    color: '#FFD740',
  },
  {
    id: 'travel',
    name: 'Travel',
    description: 'Destinations and experiences',
    icon: '🌍',
    isAdult: false,
    color: '#40C4FF',
  },
  {
    id: 'memes',
    name: 'Memes & Humor',
    description: 'Funny content and laughs',
    icon: '🤣',
    isAdult: false,
    color: '#FFAB40',
  },
  {
    id: 'adult',
    name: 'Free Zone (+18)',
    description: 'Adult content',
    icon: '🔞',
    isAdult: true,
    color: Colors.adult,
  },
];
